### ISSUE TITLE
2023年6月13・14日Step1講習会

### ISSUE THREAD

**Issue by KotaTsuboi** [shiroi36/REAL4#12]
### 資料
1)1日目説明資料：[230613_Real4講習会基本入力マニュアル【Step1】.pdf](https://github.com/shiroi36/REAL4/files/11743156/230613_Real4.Step1.pdf)
> 1日目はこちらの資料の手順通りに講師のデモンストレーションのもと入力練習しました。

2)2日目練習課題：[230614_物件入力練習.pdf](https://github.com/shiroi36/REAL4/files/11743158/230614_.pdf)
> 2日目はこちらの練習課題に各個人で取り組みました。4つの物件課題があるので各人好きなものを選択しました。

3)2日目練習課題見本：[230614_物件入力練習(作図参考一般図).pdf](https://github.com/shiroi36/REAL4/files/11743157/230614_.pdf)
> 2)の出力図面の見本です。

4)自己評価シート：[230614_SFスクール報告書【自己評価シート】.pdf](https://github.com/shiroi36/REAL4/files/11743160/230614_SF.pdf)
> 2日目の終わりに配布されたシートです。各々の理解度を自分で把握するために使用して下さいとのことでした。

5)2023年7月6日時点での報告書データ一式：[2023年7月7日報告書データ一式.zip](https://github.com/shiroi36/REAL4/files/11975406/2023.7.7.zip)
6)最終提出verの報告書：[2023年6月13日講習会報告書.docx](https://github.com/shiroi36/REAL4/files/11999351/2023.6.13.docx)
[2023年6月13日講習会報告書.pdf](https://github.com/shiroi36/REAL4/files/11999359/2023.6.13.pdf)

### 工程
- 13日：
    - 10:00~12:00：基本入力マニュアルStep1をもとに練習
    - 12:00~13:00：昼休憩
    - 13:00~16:00：基本入力マニュアルStep1をもとに練習
- 14日：
    - 10:00~12:00：各自物件入力練習
    - 12:00~13:00：昼休憩
    - 13:00~16:00：各自物件入力練習

### 2日目練習物件
- 石川：課題4
- 川崎：課題2
- 佐藤：課題2
- 坪井：課題3

***
- [x] 何の資料かわからないので、1)～4)の参照に説明を加えてください。
- [x] ①当日でた質問、行った質問を以下にまとめてください。

~~~
ここに書いてもらうか、本ページ下部コメント入力欄に記入願います。坪井さん川崎さん石川さん佐藤さん
書き方がわからなかったら最悪メールで荒木arakik@itec-c.co.jpに返信してください。

--

入力に関する質疑：

Q. 仮階の設定時の挙動は仮通りと同じですか。
A. 同じです。

Q. 通りの設定時に自動的に連番にしてくれますが、例えばPX1の次はPX2にしてくれますか。Aの次はBにしてくれますか。
A. はい。

Q. 通りを修正して動かしたら部材は連動して動きますか。
A. 節点に連動している柱・大梁は連動します。小梁は連動しません。

Q. 1FLとGLを両方設定できますか。
A. 1FLとGLを両方設定すると柱をそれぞれの階で計2回入力することになるため、おすすめしません。

Q. 基礎のモデリングはできますか。
A. 基礎梁のモデリングはSRC対応鍵があれば可能です。基礎フーチングは不可です。

Q. 見下げ視点での入力はできますか。
A. できません。

Q. 継手設定について、あらかじめ梁ごとにデフォルトの継手を設定しておいて、一括でデフォルト設定するようなことはできますか。
A. できません。やるとすれば、共通マスタの継手を梁ごとに1つのみ設定しておいてそれを選択するというやり方はあります。

Q. パラメータ更新時、パラメータを参照している部材の設定もただちに更新されますか。
A. はい。

表示に関する質疑：

Q. 入力時の部材符号表示の大きさは変えられますか。
A. 画面下にある縮尺を変更することで変えられます。実際に出力される図面の縮尺とは関係ありません。

Q. 3Dビューアのカラー設定はデバイスごとに保存されますか。物件ファイルごとに保存されますか。
A. デバイスごとに保存されます。

Q. 3Dビューアで小梁を非表示にしてもガセットが残ってしまいますが、どうしたら消せますか。
A. 3Dビューアの再描画を行うと消えると思います。

Q. 3Dビューアの起動時の表示設定が出ない場合はどこから再表示できますか。
A. 「ファイル」→「表示」から再表示の設定ができます。

作図・出力に関する質疑：

Q. 図面のレイアウトで位置を絶対値で設定できますか。
A. 左クリック長押しで「オフセット」→数値入力→矢印キー入力でできます。

Q. レイアウトを修正後図面を再作図したらレイアウトはリセットされますか。
A. 基本はリセットせずに再作図できます。

Q. 部材リストはどうやって作図しますか。
A. 梁伏図から部材リスト作図のチェックボックスをオンにします。

Q. 集計表でスタッドも集計できますか。
A. 二次部材として入力しておけば集計できます。

その他の質疑：

Q. 設定の共有はどうやってやりますか。
A. 「SFシステム転送ツール」を使います。

Q. 干渉チェックはできますか。
A. 鋼材同士の干渉チェックはできますが、ボルトの干渉はできません。将来的にも難しいと思います。

その他講習会で初めて知ったこと：
- 仮通りは、通りは作成したくないが、軸組図が欲しいときに使います。
- 階の設定における「アンカープラン階」は1F以外にアンカーを使うときに設定します。
- ピン接合は継手距離を0とします。
- 片持ち梁は鉄骨基準参照不可です。
- 梁の配置について、初期設定ではクリックの順番で梁の左右の向きは変わりません。
- アンカープラン図の「ベース縮尺」はベースプレートを強調表示したいときに使います。
- 工事管理オプションにおける「他工事からのマスタコピー」は部材リストが同じ物件の場合などで使用します（分割工事など）。
- 本柱の配置位置には交点が必要です。間柱には不要です。
- 入力時画面左下の手順表示から入力画面に移行できます。
~~~

- [x] ② #3 の観点から、有用な情報はありましたか？今後どのようなことを聞いてみようと思いましたか？

~~~
ここに書いてもらうか、本ページ下部コメント入力欄に記入願います。坪井さん
書き方がわからなかったら最悪メールで荒木arakik@itec-c.co.jpに返信してください。

-- 

積算効率化の観点からは、下記が分かりました。
- 集計表から部材重量等の集計が可能
- ボルトやスタッドに関しても集計が可能
- 工区を設定して工区ごとの集計も可能

構造図作成効率化の観点からは、下記が分かりました。
- 基礎のモデリングは基礎梁のみ可能
- 継手の一括設定は不可

下記を今後きく予定です。
- ウェブクランプ接合部を特殊部品でモデリングできるか
~~~

- [x] ③ #4  の観点から、有用な情報はありましたか？今後どのようなことを聞いてみようと思いましたか？

~~~
ここに書いてもらうか、本ページ下部コメント入力欄に記入願います。石川さん
書き方がわからなかったら最悪メールで荒木arakik@itec-c.co.jpに返信してください。

-- 

・Real4の機能ではボルト干渉のチェックは出来ない。
・3Dソリッドビューワーからデータ出力が可能、断面を指定することで部材イメージを表現出来ることが分かった。
・教材のワンポイントが分かりやすく充実しており、社内で共有したい。

~~~

- [x] ④ #5  の観点から、有用な情報はありましたか？今後どのようなことを聞いてみようと思いましたか？

~~~
ここに書いてもらうか、本ページ下部コメント入力欄に記入願います；川崎さん
書き方がわからなかったら最悪メールで荒木arakik@itec-c.co.jpに返信してください。

-- 

・Real4はMグレードファブ鉄骨製作をターゲットとしたソフトウェアであること。
・溶接基準図は単体で出力できない。(チャンピオンFABとしてまとめる際は汎用CADが適切)
・SolidWorksをベースとしている為、3DデータをAutoCADに転用する場合データ変換が必要。

~~~

- [x] ⑤ #6  の観点から、有用な情報はありましたか？今後どのようなことを聞いてみようと思いましたか？

~~~
ここに書いてもらうか、本ページ下部コメント入力欄に記入願います；佐藤さん
書き方がわからなかったら最悪メールで荒木arakik@itec-c.co.jpに返信してください。

-- 

・管理資料出力のレクチャーを受け重量表算出が出来るようになったこと。
・3Dソリッドビューワーを利用する際に工区等を指定することで視覚的な資料を作成できることがわかった。

~~~
