### ISSUE TITLE
2023年7月12・13日Step2講習会

### ISSUE THREAD

**Issue by KotaTsuboi** [shiroi36/REAL4#16]
#### 資料
1. 報告書の雛形：[2023年6月13日講習会報告書.docx](https://github.com/shiroi36/REAL4/files/11999351/2023.6.13.docx)
2. [230712_Real4講習会基本入力マニュアル【Step2】.pdf](https://github.com/shiroi36/REAL4/files/12045156/230712_Real4.Step2.pdf)
    > ブレース入力、符号管理、加工図出力の手順を示したマニュアルです。1日目から2日目午前まではこちらのマニュアルに従って講師のデモンストレーションのもと入力練習を行いました。
3. [20230713_物件入力練習資料.pdf](https://github.com/shiroi36/REAL4/files/12045293/20230713_.pdf)
    > 2日目に用いた練習課題です。2日目の午後はそれぞれ物件を1つ選択し、個人で入力練習しました。
5. [20230713_物件入力練習資料_(作図参考図面).pdf](https://github.com/shiroi36/REAL4/files/12045295/20230713_._.pdf)
    > 3.の出力例です。
7.  2023年8月8日報告書：
[2023年8月9日講習会報告書.docx](https://github.com/shiroi36/REAL4/files/12300516/2023.8.9.docx)
[2023年8月9日講習会報告書.pdf](https://github.com/shiroi36/REAL4/files/12300517/2023.8.9.pdf)
9. 添付資料①[2023年7月12日当日配付資料①_2.pdf](https://github.com/shiroi36/REAL4/files/12287452/2023.7.12._2.pdf)
10. 添付資料②[2023年7月13日当日配付資料②.pdf](https://github.com/shiroi36/REAL4/files/12287454/2023.7.13.pdf)
11. [230713_Step2物件1開始データ.zip](https://github.com/shiroi36/REAL4/files/14765746/230713_Step2.1.zip)

***
**2023年8月8日**
- [x] 5. 6. 7. を印刷してください
- [x] 参加者四人の確認印を表紙に押してください
- [x] @shiroi36 に提出してください

***
- [x] 講習会資料をアップロードします。

***
#### 工程
- 12日：
    - 10:00~12:00：水平ブレースの入力練習
    - 12:00~13:00：昼休憩
    - 13:00~15:00：鉛直ブレースの入力練習
    - 15:00~16:00：符号管理の入力練習

- 13日：
    - 10:00~12:00：符号管理の入力練習
    - 12:00~13:00：昼休憩
    - 13:00~14:00：加工図の出力練習
    - 14:00~16:00：個人で物件入力練習
    - 16:00~16:30：質疑応答

#### 練習物件
- 石川：練習1
- 佐藤：練習1
- 川崎：練習1
- 坪井：練習2

#### 講師
<img src="https://github.com/shiroi36/REAL4/assets/41675201/1ea34f50-ac2e-4939-a30f-7c762e185c30" width=480px>

#### 講習会写真
<img src="https://github.com/shiroi36/REAL4/assets/41675201/23fe5c51-dc71-41ba-a667-102e0a769cec" width=640px>
<img src="https://github.com/shiroi36/REAL4/assets/41675201/31fa6ed9-21c7-4b40-bed9-4a35d98853c2" width=640px>

***
- [x] 何の資料かわからないので、1)～4)の参照に説明を加えてください。
- [ ] ①当日でた質問、行った質問を以下にまとめてください。

~~~
ここに書いてもらうか、本ページ下部コメント入力欄に記入願います。坪井さん川崎さん石川さん佐藤さん
書き方がわからなかったら最悪メールで荒木arakik@itec-c.co.jpに返信してください。

--

Q. 他の物件ファイルで配置した部材を異なる物件ファイルにコピーペーストすることはできますか。本体合算でよいですか。
A. 他の人が行った変更を自分のファイルに取り込みたいということでしたら、本体合算を使います。丸々コピーしたいのであれば、物件ファイルごとコピーすれば良いです。

Q. 物件ファイル間の差分は見れますか。グループによる差分管理するしかありませんか。
A. REAL4の機能で差分を見る機能はありません。3DDWGに出力して外部ツールで差分を見るという方法はあります。

Q. IFCデータの表示設定はREAL4側から設定できますか。
A. 細かい設定は不可、3DDWG出力したファイル内で行う。
(製品符号まで割り振り済みであれば、製品にフォーカスし易くなる)

Q. RC+S造物件の入力はどのようにやりますか（特に仕口の入力について）。
A. SRC対応(TYPE-1)鍵であれば部材マスターにSRC柱という項目があるので、そこからできるかと思います。(アイ・テックの契約は5台中1台が対応)

Q. DWG出力時にエラーになるのですが、原因が分かりません。
A. REAL DWGがインストールできていないのが原因かもしれません。REAL4インストールDVDから関連ファイルをインストールしてください。

Q. ウェブクランプ接合部のモデル化はできますか（柱の長孔、金物、各種プレート）。
A. 作りたいものをメールでお送りいただければやり方を検討してみます。

Q. REAL4で入力しやすい物件、入力しずらい物件を教えてください。
A. 工場等は入力しやすいです。仮階が必要になる物件は入力しづらいと思います。

Q. アンボンドブレースは自分で設定するしかありませんか。
A. 既製品として用意されてはいません。端部部品から自分で設定してください。

Q. ブレースをダブルで使用した際の隙間の大きさをガセットプレートの板厚と連動させることはできますか。
A. できません。干渉チェックはできます。

Q. ブレースのガセットプレートの耳幅はどこから設定しますか。
A. ブレース配置時の入力ウィンドウに入力フォームがあります。

Q. ブレースのターンバックルは作図されませんか。
A. されません。ブレース長さはターンバックルを含めた全長で計算されます。

Q. クランク梁はどのように入力しますか。
A. 仮階を作って柱を切断します。

Q. コアの符号はコア単管の符号を参照できますか。
A. できません。

Q. 分類とグループは何が違いますか。
A. 入力の仕方が違うのみで機能は同じです。

Q. 図中のフォントはどのように変えますか。
A. 「レイヤー設定」→「文字スタイル」から変更します。

Q. REAL4からPDF出力するときの色設定はどこから行いますか。
A. 基本はレイヤの色がそのまま出力されるので、レイヤの色を変えるか、汎用CADを介してください。

Q. 画面下にある「工事別」と「配置用」は何が違いますか。
A. 配置用のパラメータを設定しておくと「配置用」を選択したときに入力画面用の表示に切り替えることができます。

その他講習で初めて知ったこと：
- Windowsの設定で「デバイス」→「マウス」→「ポイントしたときに非アクティブウィンドウをスクロールする」をオフにするとREAL4のウィンドウでスクロールが可能になる
- 図中の線に平行な線の引き方：(1)補助線(水平/鉛直線)をクリック(2)右クリック(3)図中の線を選択(4)補助線を引く
- 補助線はレイヤ設定から表示する画面を設定できる
- 「マスタ」→「一括自動取込1」でDXFの部材リストから部材マスタに取り込むことができる

~~~

- [ ] ② #3 の観点から、有用な情報はありましたか？今後どのようなことを聞いてみようと思いましたか？

~~~
ここに書いてもらうか、本ページ下部コメント入力欄に記入願います。坪井さん
書き方がわからなかったら最悪メールで荒木arakik@itec-c.co.jpに返信してください。

--

入力作業の省力化という観点からは、DXFの部材リストから部材リストに取り込めることが分かりました。
あらかじめよく使用する部材リストをDXFで作成しておいて、それをテンプレートとして使用するといった方法が考えられます。
WCSをモデル化するという観点からは、特殊部品の入力を9月の講習で扱うとのことだったので、事前にメールでモデル化したい項目をご相談することとしました。
~~~

- [ ] ③ #4  の観点から、有用な情報はありましたか？今後どのようなことを聞いてみようと思いましたか？

~~~
ここに書いてもらうか、本ページ下部コメント入力欄に記入願います。石川さん
書き方がわからなかったら最悪メールで荒木arakik@itec-c.co.jpに返信してください。


~~~

- [ ] ④ #5  の観点から、有用な情報はありましたか？今後どのようなことを聞いてみようと思いましたか？

~~~
ここに書いてもらうか、本ページ下部コメント入力欄に記入願います；川崎さん
書き方がわからなかったら最悪メールで荒木arakik@itec-c.co.jpに返信してください。

--
・アングルブレースGPLの作図方法で、向きを変えの現場対応に適した設定(みみ)を学べました。以降も引き続き、実務の中で経験した現場施工を意識した質問も増やしていくように努めます。
・ブレース配置時のよくある間違いについて口頭、操作で行えたことは良い経験でした。
・作図補助機能テクニックの部材芯表示設定や補助線の活用など、テキストに記載のない講師の発言には次回以降も留意し共有します。
・クランク梁の入力方法について詳しい溶接要領などは質問できなかった為Step3以降で質問します。
・一般図から詳細図に移る段階で、FAB由来の要素(溶接要領など)複数のパラメーターを管理する方法が可能なのかを深く質問します。

~~~

- [ ] ⑤ #6  の観点から、有用な情報はありましたか？今後どのようなことを聞いてみようと思いましたか？

~~~
ここに書いてもらうか、本ページ下部コメント入力欄に記入願います；佐藤さん
書き方がわからなかったら最悪メールで荒木arakik@itec-c.co.jpに返信してください。

--
・現在担当している物件がRCS造の為、質疑回答よりUSB鍵にも種類がある事が分かり、支社には対応する鍵が一つしかない為増台を検討する価値はあると思いました。
・ブレースシートを一体化する操作は工場の製作側に着目し、一体化するとしない双方のメリット・デメリットを自分でも発見できると感じました。
・step2のマニュアル巻末付録より前回入力したデータと更新したデータの比較ができることを学びました。
データが保存される時は保存日時でデータ管理される為「ファイル」→「名前を付けて保存」で保存しデータを比較すると記憶しやすい。比較を行った場合、新規（過去に同じデータ無）・新規（過去に同じデータ有）・形状が変わったデータで判別しそれぞれ別着色で表示される。

~~~
