### ISSUE TITLE
2023年8月24～25日REAL4Step3講習会

### ISSUE THREAD

**Issue by shiroi36** [shiroi36/REAL4#23]
前回は #16 
次回は #24 

#### 資料
1. 報告書の雛形：[2023年6月13日講習会報告書.docx](https://github.com/shiroi36/REAL4/files/11999351/2023.6.13.docx)
2.  #16 報告書：
[20230824REAL4講習会.pdf](https://github.com/shiroi36/REAL4/files/12570907/20230824REAL4.pdf)
[20230824REAL4講習会.docx](https://github.com/shiroi36/REAL4/files/12570908/20230824REAL4.docx)
4. [20230824_物件入力テスト.pdf](https://github.com/shiroi36/REAL4/files/12480825/20230824_.pdf)
> テスト物件の入力指示が記載された資料です。テスト物件は2種類あります。
5. [20230824_物件入力テスト（作図参考図面）.pdf](https://github.com/shiroi36/REAL4/files/12480826/20230824_.pdf)
> 3.の出力図面例です。
---

- [x] 講習会資料をアップロードします。

---

#### 工程
~~~
2日間にわたってテスト物件を題材とした入出力テストを行いました。
工程は各人のペースで異なりますが、下記に1例を示します。
- 2023年8月24日：
    - 10:00~10:30：通り芯・階高の入力テスト
    - 10:30~11:00：部材マスターの入力テスト
    - 11:00~12:00：部材配置の入力テスト
    - 12:00~13:00：昼休憩
    - 13:00~16:00：部材配置の入力テスト

- 2023年8月25日：
    - 10:00~12:00：各種図面の出力テスト
    - 12:00~13:00：昼休憩
    - 13:00~14:00：参考図面との比較・見直し
    - 14:30~16:00：チェックシートによる自己チェック
~~~

#### 講習内容
- 2023年8月24日：
配布された入力指示資料をもとに各人で入出力テストを行いました。出題された物件はテスト1とテスト2の2種類があり、参加者4人全員がテスト1に取り組みました。テスト1は3x1スパンの2階建ての物件で過去2回の講習で学んだ柱梁ブレースの入力が総復習できる内容となっていました。テストを行う中で、疑問点が生じた際には各自講師に質問しながら進めました。

- 2023年8月25日：
24日に引き続き入出力テストを行い、主に一般図および詳細図の出力テストを行いました。石川様はテスト2の入出力にも取り組みました。テスト2は6x1スパンの2階建ての物件で、テスト1と比較して片持ち小梁やEV・階段周りの架構などの複雑な架構がある物件です。午後の最後の時間では用意されたチェックシートに沿って正しく入力できているかを自己チェックしました。本チェックシートは講師に提出済みで1ヶ月後を目途に返却されます。

#### 題材とした物件
- 石川：テスト1、テスト2
- 佐藤：テスト1
- 川崎：テスト1
- 坪井：テスト1

#### 講習会写真
<img src="https://github.com/shiroi36/REAL4/assets/41675201/68cb4699-6980-439b-b9e3-7a6240f32a32" width="400px">
<img src="https://github.com/shiroi36/REAL4/assets/41675201/59e1a908-f01e-4201-a156-0ca3a7970300" width="400px">
<img src="https://github.com/shiroi36/REAL4/assets/41675201/184ba354-7cd7-4d9b-8399-bc975dbaeb4a" width="400px">

---

- [x] 何の資料かわからないので、1)～4)の参照に説明を加えてください。
- [x] ①当日でた質問、行った質問を以下にまとめてください。

~~~
Q. 該当箇所の存在しない継手は継手基準図に作図されますか。
A. 継手基準図の作図時設定で「作図モード」を「入力データ」とすると配置された継手のみ作図し、「マスター」とすると入力した継手をすべて作図します。

Q. 継手の共通読込の候補は何をもとに表示しているのでしょうか。
A. 主材のサイズをもとに表示していると思います。

Q. 伏図にSTLが表示されるのは上下数値を変更したときでしょうか。表示しない方法はありますか。また、FLからの数値とすることはできますか。
A. 梁伏図の梁レベル表示については「作図パラメーター」の「梁伏図」で設定が可能です。表示の有無は「梁上下表示」で設定します。レベルの基準は「梁上下位置」で設定します。

Q. ガイド図が真っ白で何も表示されないデバイスがあるのですが、原因は何でしょうか。
A. ガイド図の入っているフォルダ（C:\SFSystem\SFREAL4\Master\Fig）の画像が何かしらの原因で削除されていると思われます。他のデバイスからコピーすれば直ると思います。

Q. ブラケットの材種・寸法を接続する梁と異なるものにすることはできますか。
A. 梁マスターで「梁種類」を変更することで設定できます。

Q. スプライスプレートの内添え板がない継手はどのように入力しますか。
A. 継手マスターの設定で内添え板の板厚を0にしてください。

Q. 3次元データの出力に必須な入力情報はどこまでですか。
A. 通り芯、階高までは入力する必要があります。


その他講習会で初めて知ったこと：
- 部材の基準となっている補助線を移動すると合わせて部材も移動する。
~~~

- [ ] ② #3 の観点から、有用な情報はありましたか？今後どのようなことを聞いてみようと思いましたか？

~~~
- 前半の講習3回が完了し、今回のテストで柱、梁、ブレースおよび各種継手の入力は一通りマニュアルを見ずに入力できることを確認しました。
- 未修の範囲のうち、実務上積算が必要と考えられるものは、(1)溶接長(2)WCS金物(3)ブドウ棚等の付帯鉄骨(4)吊りピース等の仮設金物が挙げられ、これらの入力について今後確認します。
~~~

- [ ] ③ #4  の観点から、有用な情報はありましたか？今後どのようなことを聞いてみようと思いましたか？

~~~
ここに書いてもらうか、本ページ下部コメント入力欄に記入願います。石川さん
書き方がわからなかったら最悪メールで荒木arakik@itec-c.co.jpに返信してください。

・今回の講習でこれまで勉強してきた基本的な本体の入れ方をしっかり復習することができた。
・合番の振り方や製品名などの入力の理解が足りないことを改めて感じました。
・次回の胴縁や母屋の入力はほとんど触ったことがないので、予習復習をしっかりしていきたいと思います。

~~~

- [ ] ④ #5  の観点から、有用な情報はありましたか？今後どのようなことを聞いてみようと思いましたか？

~~~
ここに書いてもらうか、本ページ下部コメント入力欄に記入願います。川崎さん
書き方がわからなかったら最悪メールで荒木arakik@itec-c.co.jpに返信してください。

・ガイド図が表示されない部分について解決出来たことがとても助かりました。
・一般図から原寸までを一元化する際の開先基準は原則1物件に1つまでしか登録できませんが
　図面出力の際に既存の2次元CADデータを組み込めることを学びました。
・Real4は簡易的な鉄骨3Dモデルを作成することにも長けており
　3次元dwg出力が可能なことから、部分詳細を説明する資料作成にも役立てられると感じました。
・次回Step4以降の範囲では支持ガセットや胴縁、母屋周りの納まりについて学ぶ予定です
　胴縁やパラペット部分は2次元CADの作図と比べ、作図効率が良さそうなので疑問点を残さぬように努めます。

~~~

- [ ] ⑤ #6  の観点から、有用な情報はありましたか？今後どのようなことを聞いてみようと思いましたか？

~~~
ここに書いてもらうか、本ページ下部コメント入力欄に記入願います；佐藤さん
書き方がわからなかったら最悪メールで荒木arakik@itec-c.co.jpに返信してください。

・今まで部材入力後、部材配置でミスをしてしまった場合の対処法を該当主材の修正を選択し、ＸＹ方向を修正していたが
　補助線を利用することで部材を正規の位置まで移動できる事で修正の選択しが増えました。
・今回の物件入力で作図工程を省略せず、一つ一つの工程で入力を進めましたが、まとめて選択から配置・削除・修正の
　利便性を強く感じました。
・3回目で月に2日の講習会では普段からReal4を活用する、もしくは社内勉強会と時間を設けないと
　あまり操作の記憶が定着してこないと思いました。


~~~
