### ISSUE TITLE
2023年9月13・14日Step4講習会

### ISSUE THREAD

**Issue by KotaTsuboi** [shiroi36/REAL4#24]
前 #23 
次 #26 
#### 資料
1. 今回報告書：[2023年9月13日報告書.docx](https://github.com/shiroi36/REAL4/files/12810973/2023.9.13.docx)
2. 報告書の雛形：[2023年6月13日講習会報告書.docx](https://github.com/shiroi36/REAL4/files/11999351/2023.6.13.docx)
3. #16 報告書：
4. 当日配付資料：下記の3つの手順書に従って講師の画面共有とともに入力練習しました。
[230913_Real4講習会基本マニュアル【Step4】 .pdf](https://github.com/shiroi36/REAL4/files/12720413/230913_Real4.Step4.pdf)
[230914_Real4講習会基本マニュアル【Step4】 .pdf](https://github.com/shiroi36/REAL4/files/12720411/230914_Real4.Step4.pdf)
[230914_Real4講習会基本マニュアル【Step4】  (2).pdf](https://github.com/shiroi36/REAL4/files/12720412/230914_Real4.Step4.2.pdf)

5)提出版資料は以下となります。

[REAL4報告書2023年10月16日.docx](https://github.com/shiroi36/REAL4/files/12914040/REAL4.2023.10.16.docx)
[REAL4報告書2023年10月16日.pdf](https://github.com/shiroi36/REAL4/files/12914041/REAL4.2023.10.16.pdf)
[添付資料.pdf](https://github.com/shiroi36/REAL4/files/12914042/default.pdf)

6)zipR4データ[230913_Step4-1.zip](https://github.com/shiroi36/REAL4/files/14765759/230913_Step4-1.zip)
[230914_Step4-2.zip](https://github.com/shiroi36/REAL4/files/14765764/230914_Step4-2.zip)

---

- [x] 講習会資料をアップロードします。

---

<img src="https://github.com/shiroi36/REAL4/assets/41675201/c292790f-51cb-408e-b30b-143bb9968754" width=480pt>
<img src="https://github.com/shiroi36/REAL4/assets/41675201/52f84779-c9f2-44f1-b9fc-6f04cd28d619" width=480pt>

#### 工程記入例
~~~
- 2023年9月13日：
    - 10:00~11:00：ハンチスタイルの設定
    - 11:00~12:00：継手・仕口詳細設定
    - 12:00~13:00：昼休憩
    - 13:00~15:00：仮設金物・特殊部品の入力
    - 15:00~16:00：工区塗装の設定

- 2023年9月14日：
    - 10:00~11:00：クレーンガーダーの入力
    - 11:00~12:00：センタージョイント梁の設定
    - 12:00~13:00：昼休憩
    - 13:00~14:00：合掌梁の入力
    - 14:00~14:30：エレクションピースの入力
    - 14:30~15:00：支持ガセット・接続ガセットの入力
    - 15:00~15:30：ボルト発注明細の出力
    - 15:30~16:00：質疑応答
~~~

#### 講習内容
```
講習は2日間ともレクチャー形式で行われ、講師の画面共有のもと入力練習を行いました。
- 2023年9月13日：
手順書「基本入力マニュアル【Step4】 - ハンチスタイル・各詳細設定・二次部材・工区塗装編 -」に沿って入力練習しました。2層2x1スパンの建物を題材として、大梁端部のハンチ設定、継手・仕口の詳細設定、仮設金物・特殊部品の入力、工区塗装の設定をしました。
- 2023年9月14日：
2冊の手順書「基本入力マニュアル【Step4】様々な入力ケース①・②」に沿って入力練習しました。①の手順書では2層4x3スパンの建物を題材として、クレーンガーダーの入力、ブラケット同士が接続するセンタージョイントの設定、合掌梁の設定をしました。②の手順書では5層6x3スパンの建物を題材として、エレクションピースの入力、間柱の支持ガセットの入力、ボルト発注明細の出力をしました。
```

- [x] 何の資料かわからないので、1)～4)の参照に説明を加えてください。
- [ ] ①当日でた質問、行った質問を以下にまとめてください。

~~~
Q. WCS金物類はどのように入力できますか（事前質問）。
A. 「特殊部品」から入力できます。例えば金物であれば、「板部品」タブでDXFをインポートして底板と垂直板を作成し、「特殊部品」タブで板を2つ組み合わせて部品を作成することができます。

Q. 仮ボルトの配置ルールはどこにありますか。
A. 「共通・工事別マスター」→「ボルト」の中で指定します。

その他講習会で初めて知ったこと：
- ハンチ高さの上限値はパラメータの「データ作成」→「柱・梁作成」→「垂直ハンチ合わせ」から設定する
- ブドウ棚の吊り材等で間柱のBPLをなくしたいときは「本体入力」→「詳細設定」→「アンカーベース」で「ベース」を「無し」に設定する
- 穴セット作成時にタイプをボルトマスターとすれば任意の位置にボルトを配置可能
- 特殊部品作成時は「ファイル取り込み」から板部品のDXFをインポート可能
- ドットウェルホームページの「よくあるご質問」ページにREAL4で出力する管理資料の活用例がある
~~~

- [ ] ② #3 の観点から、有用な情報はありましたか？今後どのようなことを聞いてみようと思いましたか？

~~~
- WCS物件の積算・作図のため、WCS金物やプレート類の入力方法を質問し、入力は特殊部品や穴セットによるボルト配置を使用すれば不可能ではないことがわかりました。
- 入力には手間がかかりそうだったため、特殊部品のテンプレートを用意しておけば時間が短縮できるのか、手計算で見積もる場合と比べて時間が短縮されるか等を検討する必要があると感じました。
- 次回の質問として、特定の符号の大梁に一括で特殊部品を配置するといった配置方法ができるのか質問します。
~~~

- [ ] ③ #4  の観点から、有用な情報はありましたか？今後どのようなことを聞いてみようと思いましたか？

~~~
・カバープレートに関しては入力はできるが細かい設定等ができないのでREAL4での入力は厳しいと思いました。
・二次部材に関してはできることとできないことを見極め、どこまでをREAL4で入力するかを考える必要があると思いました。
・特殊部品を使うことで様々なものを表現できるようになるになるので、やれることの幅が広がると思いました。
~~~

- [ ] ④ #5  の観点から、有用な情報はありましたか？今後どのようなことを聞いてみようと思いましたか？

~~~
・特殊部品の操作を学んだことで他物件のマスターを参照できるようになり、入力速度が向上しました。
・次回の範囲では胴縁、母屋部材の入力を学習予定なので物件ファイル分割やデータ統合を中心に
疑問を残さないように質問していきます。
・Real4では作図出来ない図面を汎用CADデータから引用しReal4を経由して吐き出す方法を学びました。
・Real4を実務に活用する場合、パラメータ等の初期設定を共通化する必要があることを改めて感じました
可能であれば自社での過去物件や他社の入力方法、他社の活用事例なども取り入れたいです。
~~~

- [ ] ⑤ #6  の観点から、有用な情報はありましたか？今後どのようなことを聞いてみようと思いましたか？

~~~
・使用しているver.によって表示形式や項目の追加がある為、講習会ではマニュアル通りの進行とは異なった手順で作業する場面がありました。
・工区割設定後、発注書作成時パラメーター設定より工区ごとの発注書を作成できることがわかりました。
~~~

### 質問事項
- [WCSのパンフレットPDF](https://www.itec-c.co.jp/download/wcs.pdf)を送ります。これの(1)金物(2)柱の長孔(3)柱フランジ補強板(4)柱ウェブ補強板(5)ボルトのモデル化はできますか。
