### ISSUE TITLE
2023年10月11日・24日講習会

### ISSUE THREAD

**Issue by KotaTsuboi** [shiroi36/REAL4#25]
前 #24 

#### 資料
- [ ] 講習会資料をアップロードします。

#### 工程記入例
~~~

~~~

#### 講習内容
```

```

- [ ] ①当日でた質問、行った質問を以下にまとめてください。

~~~

~~~

- [ ] ② #3 の観点から、有用な情報はありましたか？今後どのようなことを聞いてみようと思いましたか？

~~~

~~~

- [ ] ③ #4  の観点から、有用な情報はありましたか？今後どのようなことを聞いてみようと思いましたか？

~~~

~~~

- [ ] ④ #5  の観点から、有用な情報はありましたか？今後どのようなことを聞いてみようと思いましたか？

~~~

~~~

- [ ] ⑤ #6  の観点から、有用な情報はありましたか？今後どのようなことを聞いてみようと思いましたか？

~~~

~~~

### 質問事項
- 特定の部材に一括で特殊部品を配置することはできますか。
- ボルトのデフォルトをトルシアにできませんか。
- 既製品仕口のデータはどこにありますか。
