### ISSUE TITLE
2023年10月11日/24日Step5講習会

### ISSUE THREAD

**Issue by shiroi36** [shiroi36/REAL4#26]
前 #24 
1)報告書：[2023年10月11日講習会報告書.docx](https://github.com/shiroi36/REAL4/files/13329859/2023.10.11.docx)
2)添付資料：[2023年10月11日講習会報告書_添付資料.docx](https://github.com/shiroi36/REAL4/files/13329785/2023.10.11._.docx)
[2023.10.11REAL4講習会報告書_ファイル場所.pdf](https://github.com/shiroi36/REAL4/files/14105600/2023.10.11REAL4._.pdf)
[2023.10.11REAL4講習会報告書.pdf](https://github.com/shiroi36/REAL4/files/14105601/2023.10.11REAL4.pdf)
3)zipR4データ
[231011_Step5-1.zip](https://github.com/shiroi36/REAL4/files/14765785/231011_Step5-1.zip)
[231024_Step5-2.zip](https://github.com/shiroi36/REAL4/files/14765814/231024_Step5-2.zip)

***
#### 資料
1. 1日目配布資料1：[231011_Real4講習会基本マニュアル【Step5】  (胴縁).pdf](https://github.com/shiroi36/REAL4/files/13264665/231011_Real4.Step5.pdf)
2. 1日目配布資料2：[231011_Real4講習会基本マニュアル【Step5】  (母屋).pdf](https://github.com/shiroi36/REAL4/files/13264666/231011_Real4.Step5.pdf)
3. 2日目配布資料1：[20231025_STEP5-物件入力練習1.pdf](https://github.com/shiroi36/REAL4/files/13264655/20231025_STEP5-.1.pdf)
4. 2日目配布資料2：[20231025_STEP5-物件入力練習2.pdf](https://github.com/shiroi36/REAL4/files/13264657/20231025_STEP5-.2.pdf)
5. 2日目配布資料3：[20231025_STEP5-物件入力練習2(作図参考図面).pdf](https://github.com/shiroi36/REAL4/files/13264660/20231025_STEP5-.2.pdf)
6. 2日目配布資料4：[20231025_STEP5-物件入力練習3.pdf](https://github.com/shiroi36/REAL4/files/13264661/20231025_STEP5-.3.pdf)
7. 2日目配布資料5：[20231025_STEP5-物件入力練習3(作図参考図面).pdf](https://github.com/shiroi36/REAL4/files/13264663/20231025_STEP5-.3.pdf)

上記の支社サーバのアップロード先
```
1. I:\川崎李伊\★Real4講習会\231011_Step5-1\231011_Real4講習会基本マニュアル【Step5】  (胴縁).pdf
2. I:\川崎李伊\★Real4講習会\231011_Step5-1\231011_Real4講習会基本マニュアル【Step5】  (母屋).pdf
3. I:\川崎李伊\★Real4講習会\231024_Step5-2\20231025_STEP5-物件入力練習1.pdf
4. I:\川崎李伊\★Real4講習会\231024_Step5-2\20231025_STEP5-物件入力練習2.pdf
5. I:\川崎李伊\★Real4講習会\231024_Step5-2\20231025_STEP5-物件入力練習2(作図参考図面).pdf
6. I:\川崎李伊\★Real4講習会\231024_Step5-2\20231025_STEP5-物件入力練習3.pdf
7. I:\川崎李伊\★Real4講習会\231024_Step5-2\20231025_STEP5-物件入力練習3(作図参考図面).pdf
```

報告書の雛形：[2023年6月13日講習会報告書.docx](https://github.com/shiroi36/REAL4/files/11999351/2023.6.13.docx)

***
#### 工程

- [x] 以下の工程例を参考に当日の行程を記述してください

~~~
- 2023年10月11日：
    - 10:00~10:30：質疑応答
    - 10:30~11:00：母屋部材登録
    - 11:00~12:00：母屋配置
    - 12:00~13:00：昼休憩
    - 13:00~13:30：胴縁部材登録
    - 13:30~16:00：胴縁配置

- 2023年10月24日：
    - 10:00~11:00：質疑応答
    - 11:00~11:30：符号名の設定
    - 11:30~12:00：各種図面出力
    - 12:00~13:00：昼休憩
    - 13:00~16:00：各自入力練習
~~~

***
#### 講習内容
- 2023年10月11日：
手順書「基本入力マニュアル【Step5】-母屋・胴縁編-」に沿って講師の画面共有のもと入力練習しました。2層2x1スパンの建物を題材として、母屋・胴縁の作成・配置をしました。

- 2023年10月24日：
1日目と同じ手順書・物件を用いて講師の画面共有のもと母屋胴縁の符号名の設定と母屋胴縁に関する各種図面の出力を行いました。午後からは各自で今回の範囲の入力練習を行いました。石川様は物件3、川崎様と佐藤様は物件1、坪井様は物件2を入力しました。

***
#### 講習会写真
<img src="https://github.com/shiroi36/REAL4/assets/41675201/40090dde-7b3c-45f5-b81c-310339b96689" width=480px>
<img src="https://github.com/shiroi36/REAL4/assets/41675201/f3d618d4-2c41-4e80-81d9-2dcfab30a480" width=480px>
<img src="https://github.com/shiroi36/REAL4/assets/41675201/28fb977a-396d-4aef-84e5-ef36e9ab5c1e" width=480px>

---
- [x] 配付資料をアップロードしてください
- [ ] 配付資料の説明を追加してください
- [x] 当日でた質問および行った質問を以下にまとめてください

~~~
Q. 部材マスター入力時のボルトのデフォルト値をTC（トルシア形高力ボルト）にできませんか。
A. ボルトマスターで変更することはできますが、他の環境とのファイルの受け渡し時に問題がないか、開発元に聞いてみます。

Q. シャッターを入力する際に縦材のベースプレート・アンカーボルトの設定はできませんか。
A. 「修正」→「コーナーピース」→「ピース種類」を「ベース」にすれば、設定できます。

Q. シャッターを入力する際に縦材が上の横材まで伸びないことがありますが、原因はわかりますか。
A. 開口マスターの設定で部材の通し関係がうまく設定できていないかと思います。

その他講習会で初めて知ったこと：
- ST-Bridgeで読み込むと梁継手は「簡易継手」として設定される
- 入力シートの「一般」タブを右クリックすると表示項目を設定可
~~~

***
- [ ] ② #3 の観点から、有用な情報はありましたか？今後どのようなことを聞いてみようと思いましたか？

~~~
建築構造分野の標準データ形式である「ST-Bridge」データの読込について新しい情報が得られました。
ST-Bridgeの梁の継手データは読込不可であるものの、「簡易継手」と呼ばれる継手としてREAL4上に読み込まれることが分かりました。
その後の調査でこの「簡易継手」は各梁寸法に対するデフォルト継手にあたるものであり、SCSS標準継手等を適切に設定すれば継手データの読込もスムーズにできることがわかりました。
簡易継手の設定方法やそのREAL4内での取り扱いへの理解が浅いため、次回講習で明らかにします。
~~~

- [ ] ③ #4  の観点から、有用な情報はありましたか？今後どのようなことを聞いてみようと思いましたか？

~~~
シャッター開口を入力するときに、あらかじめ横胴縁か縦胴縁を入力しなければうまく配置できないので工夫が必要だと感じました。
また、シャッターのRC取り合いについて、ベースをPLで設定はきるが、アングル材では登録ができないのでこちらも工夫が必要だと感じました。


~~~

- [ ] ④ #5  の観点から、有用な情報はありましたか？今後どのようなことを聞いてみようと思いましたか？

~~~
胴縁入力機能は、シャッターなどの他付帯基準図作図に有効活用出来ます
開口周りのピース修正操作にクセはあるものの、慣れれば効率よく修正が出来る反面
ボルト同士の干渉やピース溶接、現場施工性など
一見入力出来るが製作・施工に不適な部分には注意が必要だと感じました。
母屋・胴縁の入力作業は複数人ではなく、一人の人間に任せる方が間違いが減ると考えます。

今回までで基本マニュアル一式の履修が終わり
Real4を活用した作図作業効率化に胴縁・母屋・ブレース図は適していると感じました
また、入力作業を行う中で製作に特化したツールである印象が大きく
実務で活用するには業務の責任所在を明確化した契約・役割分担
(例：一般図・付帯基準図作図までアイ・テック設計課、詳細図・原寸をFAB)
をすることが重要だと考えます。

次回の講習では、業務内でBIM連携についての疑問がありますので
Real4を自社で活用する場合の留意点と合わせて質問していきます。

~~~

- [ ] ⑤ #6  の観点から、有用な情報はありましたか？今後どのようなことを聞いてみようと思いましたか？

~~~
胴縁・母屋の入力から部材配置までの流れはCADと比較すると勾配設定、割付寸法の設定、
部材配置後の干渉チェックを行うことで間違い、見落としが軽減される意味でReal4の方が効率がよいと思いました。
胴縁・母屋のボルトは中ボルト仕様が現場で支流だが、Dlock、T-スプリング、スマートハイパーロードナット等
緩み止め防止の特殊部品をReal4に反映する事は可能なのか、次回の講習で質疑しようと思いました。



~~~
