### ISSUE TITLE
2023年11月15・16日Step6講習会

### ISSUE THREAD

**Issue by KotaTsuboi** [shiroi36/REAL4#27]
前 #26

***
#### 資料
1)報告書：
[2023年11月15日講習会報告書.docx](https://github.com/shiroi36/REAL4/files/14756446/2023.11.15.docx)
[2023年11月15日講習会報告書.pdf](https://github.com/shiroi36/REAL4/files/14756447/2023.11.15.pdf)
2)別紙資料：
[2023年11月15日別紙資料.docx](https://github.com/shiroi36/REAL4/files/14756451/2023.11.15.docx)
[2023年11月15日別紙資料.pdf](https://github.com/shiroi36/REAL4/files/14756452/2023.11.15.pdf)
3)報告書の雛形：[2023年6月13日講習会報告書.docx](https://github.com/shiroi36/REAL4/files/11999351/2023.6.13.docx)
4)zipR4
[231115_Step6入力テスト1.zip](https://github.com/shiroi36/REAL4/files/14765827/231115_Step6.1.zip)
[231115_Step6入力テスト2.zip](https://github.com/shiroi36/REAL4/files/14765828/231115_Step6.2.zip)
[231115_Step6入力テスト3.zip](https://github.com/shiroi36/REAL4/files/14765829/231115_Step6.3.zip)
[231116_Step6入力テスト1入力後.zip](https://github.com/shiroi36/REAL4/files/14765836/231116_Step6.1.zip)
[231116_Step6入力テスト2入力後.zip](https://github.com/shiroi36/REAL4/files/14765837/231116_Step6.2.zip)
[231116_Step6入力テスト3入力後.zip](https://github.com/shiroi36/REAL4/files/14765838/231116_Step6.3.zip)

***
#### 工程

- [x] 以下の工程例を参考に当日の行程を記述してください

~~~
入力練習は各自のペースで行いました。下記に一例を示します。

- 2023年11月15日：
    - 10:00~10:30：質疑応答
    - 10:30~11:00：クレーンガーダー配置練習
    - 11:00~12:00：梁ハンチ設定練習
    - 12:00~13:00：昼休憩
    - 13:00~16:00：二次部材配置練習

- 2023年11月16日：
    - 10:00~11:00：メッキ範囲の設定練習
    - 11:00~12:00：胴縁の入力練習
    - 12:00~13:00：昼休憩
    - 13:00~14:00：符号設定練習
    - 14:00~16:00：継手基準図、部品図、胴縁割付図、胴縁加工図、型紙作図練習
~~~

***
#### 講習内容

***
#### 講習会写真
<img width=480px src="https://github.com/shiroi36/REAL4/assets/41675201/f67721d7-72c0-48fe-a4fe-c57f362685bb">
<img width=480px src="https://github.com/shiroi36/REAL4/assets/41675201/37338cfa-756c-4d06-877c-3bdb731bbeda">

---
- [x] 配付資料をアップロードしてください
- [x] 配付資料の説明を追加してください
- [x] 当日でた質問および行った質問を以下にまとめてください

~~~
Q. 継手マスターの「簡易継手」ボタンがあり、簡易継手をいっぺんに割り振ることができることがわかりました。割り振られる継手はどこで設定できますか。
A. 共通読込の継手の一番上の継手を読み込んでいると思われます。特定の継手に割り振りたい場合は共通読込の継手をその継手のみにします。

Q. ST-Bridgeで読み込んだところ、小梁の接続先情報がインポートされませんでした。1つ1つの小梁の接続情報変更する以外に設定方法はありませんか。
A. ありません。

Q. 梁フランジスタッド入力で「フランジ幅<200なら1列、それ以外は2列」という条件で一括で入力できませんか。
A. できません。

Q. 胴縁や母屋に使用する中ボルトで緩み止め防止としてDlock、T-スプリング、スマートハイパーロードナットを弊社から質疑、またはゼネコンより御指示頂きます。Real4に反映したいと考えた時、特殊部品として作図するのか今後のバージョンアップに向けての御依頼となるのでしょうか。
A. ボルトマスターでボルトとして登録すれば入力できるかと思います。Dlockについてはボルトの材種として用意されています。
~~~

***
- [ ] ② #3 の観点から、有用な情報はありましたか？今後どのようなことを聞いてみようと思いましたか？

~~~
構造データの標準フォーマットであるST-Bridgeの読込時に小梁のガセットが読み込まれないことについて、
効率的な修正方法はなく、1つ1つ手作業で追加する必要があるとわかりました。
梁スタッドについてもフランジ幅によって列数を切り替える効率的な入力方法はなく、
梁ごとに入力する必要があるとわかりました。
~~~

- [ ] ③ #4  の観点から、有用な情報はありましたか？今後どのようなことを聞いてみようと思いましたか？

~~~
図面枠の作成方法について、教えてもらうことができ今後とても使える技術だと思いました。
同じ形でも入力方法が何パターンもあり、入力のやり方によっては、のちの入力に影響を及ぼすものもあるため、
入力方法を見極める必要があると感じました。
~~~

- [ ] ④ #5  の観点から、有用な情報はありましたか？今後どのようなことを聞いてみようと思いましたか？

~~~
・前回提出していた、図面枠（記事項変数を用いた仮作図データ）を受領しました
この図面枠の他、従来の汎用CADを活用するために分からないことは講習後もメールで質問していきます。

・3次元データの提出をゼネコンから依頼される場合
各FABの最終的なREAL4データを吸い上げて物件データを合算すると、パラメータに不整合が起きるため
個別にIFCを提出するか、詳細図以下FAB側が入力する場合は
パラメータの変更に制限を設ける必要があることがわかりました。

・構造データをREAL4へ最速入力する場合の方法と要素を考えました
①ST-Bridge（.stb）フォーマットを用意する
　(型鋼またはある程度の径を持つ部材で、指定クラスのオブジェクトに限る)
②通り情報と階高、パラメータを確認する
③継手情報を一括入力でCSVで読み込む
④簡易継手で読まれているものをマスターから修正する
⑤入力されない要素を補う
⑥各FAB割やFAB独自の設定、その他項目を設定する

~~~

- [ ] ⑤ #6  の観点から、有用な情報はありましたか？今後どのようなことを聞いてみようと思いましたか？

~~~
クレーンガーター梁配置後、切断し、片持ち梁と部材接合する際
先に片持ち梁とガーター梁を接合後、切断を行ってしまうと孔位置が片側のガーター梁にもっていかれてしまう。
確認方法は箇所の梁詳細図を出力し表示確認をした際確認できる。

~~~
